configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/sambanova%2Fsambanova-ed892a8828f5ca3d2da37164acacea0ddb4c6d8dde76e092eccea7ee9fd35897.yml
openapi_spec_hash: 8057a6899dea53cc8cc1be7ddfb801c8
config_hash: 59dfb724942eeb9c5dc372eb7e25d48a
