configured_endpoints: 1
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/sambanova%2Fsambanova-ee3cb52e75acb83482e1beedc87b0cdcc76af1ddef7bb2209753c7ede48cf24f.yml
openapi_spec_hash: 8a3b0681f9c20e57a6347cc73bd08a23
config_hash: 8e1931fe8ca88d9e3b7cf34d83bbde86
